version: "3.7"

services:
  node:
    image: "node:8"
    user: "node"
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
    ports:
      - 8081:8081
    command: "/bin/bash -c 'npm install && npm start'"
